name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: ref
      - name: Echo branch
        run: echo "${{ steps.ref.outputs.branch }}"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CSET_ANALYTICS_ACCESS_TOKEN }}
          repository: cisagov/cset-analytics-cicd
          event-type: deploy
          client-payload: '{"trigger": "cset-analytics-api", "env": "${{ steps.ref.outputs.branch }}"}'
